# config.yml

train_dir: '/mnt/working/poddarm/raw dataset/train'
test_dir: '/mnt/working/poddarm/raw dataset/test'
batch_size: 64


layers:
  - type: Conv2D
    filters: 32
    kernel_size: [3, 3]
    padding: SAME
    input_shape: [227, 227, 3]
    strides: [1, 1]
    activation: relu
    dilation_rate: 3

  - type: MaxPooling2D
    pool_size: [2, 2]
    padding: SAME
  - type: Conv2D
    filters: 64
    kernel_size: [3, 3]
    padding: SAME
    strides: [1, 1]
    activation: relu
    dilation_rate: 3

  - type: MaxPooling2D
    pool_size: [2, 2]
    padding: SAME

  - type: Conv2D
    filters: 128
    kernel_size: [3, 3]
    padding: SAME
    strides: [1, 1]
    activation: relu
    dilation_rate: 3

  # - type: Conv2D
  #   filters: 32
  #   kernel_size: [3, 3]
  #   padding: SAME
  #   # input_shape: [51,51,32]
  #   strides: [1, 1]
  #   activation: relu
  - type: UpSampling2D
    size: [2, 2]

  - type: Conv2D
    filters: 64
    kernel_size: [3, 3]
    padding: SAME
    strides: [1, 1]
    activation: relu
    dilation_rate: 3

  - type: UpSampling2D
    size: [2, 2]

  - type: Conv2D
    filters: 32
    kernel_size: [3, 3]
    padding: SAME
    strides: [1, 1]
    activation: relu
    dilation_rate: 3

  - type: Conv2D
    filters: 3
    kernel_size: [2, 2]
    padding: VALID
    strides: [1, 1]
    activation: relu
    dilation_rate: 1

    
autoencoder:
  # encoder: encoder
  # decoder: decoder
  lr: 0.001
  loss: mean_squared_error
  metrics: ['accuracy']

model:
  early_stop:
    monitor: 'val_loss'
    patience: 5
  checkpoint:
    filepath: '/mnt/working/poddarm/saved_model/weights-improvements-{epoch:02d}-{val_accuracy:.4f}.hdf5'
    monitor: 'val_accuracy'
    verbose: 1
    save_best: True
    mode: 'max'
  fit:
    epochs: 30
    verbose: 1
    validation_steps: 10



# decoder:
#   layers:
#     - type: Conv2DTranspose
#       filters: 32
#       kernel_size: [3, 3]
#       padding: VALID
#       input_shape: [51,51,32]
#       strides: [1, 1]
#       activation: relu
#     - type: UpSampling2D
#       size: [2, 2]
#     - type: Conv2DTranspose
#       filters: 64
#       kernel_size: [3, 3]
#       padding: VALID
#       strides: [1, 1]
#       activation: relu
#       dilation_rate: 2
#     - type: UpSampling2D
#       size: [2, 2]
#     - type: Conv2DTranspose
#       filters: 128
#       kernel_size: [3, 3]
#       padding: VALID
#       strides: [1, 1]
#       activation: relu
#       dilation_rate: 2
#     - type: Conv2DTranspose
#       filters: 3
#       kernel_size: [4, 4]
#       padding: VALID
#       strides: [1, 1]
#       activation: relu

